language: scala

scala:
  - 2.12.8

env:
  - JDK=oraclejdk8

before_script:
  - jdk_switcher use $JDK

script: sbt ++$TRAVIS_SCALA_VERSION clean stack/clean 'testOnly -- timefactor 10' 'stack/testOnly -- timefactor 10'
